name: Feature request
description: Suggest an idea for the plugin
title: "[Feature] "
labels: ["enhancement"]
assignees: ["Rapha149"]

body:
- type: markdown
  attributes:
    value: Thanks for taking the time to submit a feature request! Please fill out the fields below.
- type: textarea
  attributes:
    label: Is your feature request related to a problem?
    placeholder: Yes, I have this problem, that ...
    render: bash
- type: textarea
  attributes:
    label: What solution would you like?
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
  validations:
    required: true
- type: textarea
  attributes:
    label: Any additional comments?
    
