name: I need help implementing the API
description: Ask a question or describe a problem you have with using the API in your project
title: "[Problem] "
labels: ["problem"]

body:
- type: input
  attributes:
    label: API version
    placeholder: 2.3.3
  validations:
    required: true
- type: input
  attributes:
    label: Server software and version
    description: e.g. Spigot, Paper, Mohist, ...
    placeholder: Spigot 1.16.5
  validations:
    required: true
- type: textarea
  attributes:
    label: What are you trying to do?
    description: Describe what you want to achieve with the API in your project.
  validations:
    required: true
- type: textarea
  attributes:
    label: What do you need help with?
    description: Describe what you struggle with and how you have tried to solve the problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Code snippets
    description: |
      If applicable, upload or paste code snippets to help explain your problem. For better formatting, please place your code inside a fenced code block like this:
      \`\`\`java
      // Code
      \`\`\`
  validations:
    required: true
- type: textarea
  attributes:
    label: Any additional comments?
